# Generated by Django 2.2.14 on 2022-11-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20221110_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(upload_to='Albums/albums_images'),
        ),
        migrations.AlterField(
            model_name='album',
            name='zip_file',
            field=models.FileField(default='', upload_to='Albums/albums_zip_files'),
        ),
        migrations.AlterField(
            model_name='albumaudio',
            name='audio',
            field=models.FileField(upload_to='Albums/albums_audios'),
        ),
        migrations.AlterField(
            model_name='albumaudio',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='albumaudio',
            name='image',
            field=models.ImageField(default='album.JPG', upload_to='Albums/albums_audios_images'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.ImageField(upload_to='Playlist/images'),
        ),
    ]
