# Generated by Django 2.2.14 on 2022-11-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20221110_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumaudio',
            name='image',
            field=models.ImageField(default='album.PNG', upload_to='Albums/albums_audios_images'),
        ),
    ]
