# Generated by Django 2.2.14 on 2022-12-08 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20221110_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumaudio',
            name='image',
            field=models.ImageField(default='playlist.PNG', upload_to='Albums/albums_audios_images'),
        ),
        migrations.CreateModel(
            name='PlaylistAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio', models.FileField(upload_to='Playlist/playlist_audios')),
                ('image', models.ImageField(default='album.PNG', upload_to='Playlist/playlist_audios_images')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='music.Artist')),
            ],
        ),
    ]
