# Generated by Django 2.2.14 on 2022-12-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20221208_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumaudio',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='musiccart',
            name='musics',
        ),
        migrations.RemoveField(
            model_name='musiccart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ordermusic',
            name='music',
        ),
        migrations.RemoveField(
            model_name='ordermusic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='music',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='music',
            name='price',
        ),
        migrations.RemoveField(
            model_name='music',
            name='type',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='price',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='type',
        ),
        migrations.AlterField(
            model_name='playlistaudio',
            name='image',
            field=models.ImageField(default='playlist.PNG', upload_to='Playlist/playlist_audios_images'),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='AlbumAudio',
        ),
        migrations.DeleteModel(
            name='MusicCart',
        ),
        migrations.DeleteModel(
            name='OrderMusic',
        ),
    ]
