# Generated by Django 2.2.14 on 2022-12-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20221215_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='download_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
