# Generated by Django 2.2.14 on 2022-12-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_playlist_download_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='download_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
