# Generated by Django 2.2.14 on 2022-11-10 17:43

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('country', django_countries.fields.CountryField(default='togo', max_length=2)),
                ('phone', models.IntegerField()),
                ('message', models.TextField(null=True)),
                ('lu', models.BooleanField(default=False)),
                ('fake', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddPremiumMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=200)),
                ('music_title', models.CharField(max_length=200)),
                ('audio', models.FileField(upload_to='marketing/premium_musics/audios')),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='marketing/premium_musics/images')),
                ('country', django_countries.fields.CountryField(default='togo', max_length=2)),
                ('music_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.MusicCategory')),
            ],
        ),
        migrations.CreateModel(
            name='AddFreeMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('audio', models.FileField(upload_to='marketing/free_musics/audios')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='marketing/free_musics/images')),
                ('country', django_countries.fields.CountryField(default='togo', max_length=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.MusicCategory')),
            ],
        ),
    ]
