# Generated by Django 2.2.14 on 2022-11-10 17:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EventTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EventVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('video', models.FileField(upload_to='Events/events_videos')),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('event_address', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('country', django_countries.fields.CountryField(default='', max_length=2)),
                ('is_sponsored', models.BooleanField(default=False)),
                ('is_on_top', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_video_category', to='event.EventCategory')),
                ('tags', models.ManyToManyField(to='event.EventTags')),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(max_length=200, upload_to='Events/events_images')),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('event_address', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('country', django_countries.fields.CountryField(default='', max_length=2)),
                ('is_sponsored', models.BooleanField(default=False)),
                ('is_on_top', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_image_category', to='event.EventCategory')),
                ('tags', models.ManyToManyField(to='event.EventTags')),
            ],
        ),
    ]
