# Generated by Django 2.2.14 on 2022-12-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='localisation',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='eventvideo',
            name='localisation',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
