# Generated by Django 2.2.14 on 2022-12-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20221215_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvideo',
            name='contact_1',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='eventvideo',
            name='contact_2',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
    ]
