# Generated by Django 2.2.14 on 2022-11-10 17:43

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('video', models.FileField(upload_to='Emission/emission_videos')),
                ('episode', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('emission_date', models.DateTimeField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(default='', max_length=2)),
                ('is_on_top', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_video_category', to='emission.EmissionCategory')),
                ('tags', models.ManyToManyField(to='emission.EmissionTags')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionPodcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('audio', models.FileField(upload_to='Emission/emission_podcasts')),
                ('episode', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(default='', max_length=2)),
                ('is_on_top', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_podcast_category', to='emission.EmissionCategory')),
                ('tags', models.ManyToManyField(to='emission.EmissionTags')),
            ],
        ),
    ]
