# Generated by Django 2.2.14 on 2022-12-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emission', '0004_emissionvideocomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionvideocomment',
            name='emission_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_video_comments', to='emission.EmissionVideo'),
        ),
    ]
