# Generated by Django 2.2.14 on 2022-11-10 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='ads',
        ),
        migrations.AlterField(
            model_name='clip',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clip_category', to='music.MusicCategory'),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_category', to='music.MusicCategory'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default=1, upload_to='Videos/videos'),
            preserve_default=False,
        ),
    ]
