# Generated by Django 2.2.14 on 2022-11-10 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20221110_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.DeleteModel(
            name='VideoCategory',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
