# Generated by Django 2.2.14 on 2022-11-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20221110_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('rs', 'Reseaux sociaux'), ('clip_t', 'Clip Teaser')], default='rs', max_length=10),
        ),
    ]
