# Generated by Django 2.2.14 on 2022-12-17 11:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20221215_2204'),
        ('video', '0004_auto_20221110_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('video', models.FileField(upload_to='Teaser/videos')),
                ('thumbnail', models.ImageField(blank=True, max_length=500, null=True, upload_to='Videos/videos_thumbnails')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20)),
                ('is_on_top', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaser_category', to='music.MusicCategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='is_sponsored',
        ),
        migrations.RemoveField(
            model_name='video',
            name='type',
        ),
        migrations.DeleteModel(
            name='VideoView',
        ),
    ]
